import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import vm from 'node:vm';
const root=join(dirname(fileURLToPath(import.meta.url)),'..');
const context=vm.createContext({URL,URLSearchParams});
for(const path of ['dist/hub-utils.js','dist/hub-data.js'])vm.runInContext(await readFile(join(root,path),'utf8'),context);
const {utils,topics,resources,paths,glossary}=vm.runInContext('({utils:hubUtils,topics:hubTopics,resources:hubResources,paths:hubLearningPaths,glossary:hubGlossary})',context);
assert.equal(utils.escapeHtml('<img src=x onerror="alert(1)"> & \'x\''),'&lt;img src=x onerror=&quot;alert(1)&quot;&gt; &amp; &#39;x&#39;');
for(const href of ['javascript:alert(1)','data:text/html,<script>alert(1)</script>','file:///etc/passwd','not a URL'])assert.equal(utils.sourceHref(href),'#');
assert.equal(utils.sourceHref('https://example.com/?q="test"&x=1'),'https://example.com/?q=%22test%22&amp;x=1');
assert(utils.matches('MNE-Python: EEG preprocessing','eeg python'));
assert(utils.matches('École neuroscience','ecole'));
assert(!utils.matches('Calcium imaging','motor EEG'));
assert.equal(utils.parseRoute('').route,'overview');
assert.equal(utils.parseRoute('#org/open%20ephys').id,'open ephys');
assert.equal(utils.parseRoute('#org/%ZZ').id,'');
assert.equal(utils.parseRoute('#resources?topic=behavior&q=3D+video').params.get('q'),'3D video');
assert.equal(utils.sourceDate('2026'),'2026');
assert.equal(utils.sourceDate('2026-09'),'2026-09');
assert.equal(utils.sourceDate(null),'Date unavailable');
assert.equal(utils.sourceDate('bad-date'),'Date unavailable');
assert.equal(utils.sourceDate('2026-09-07'),'Sep 7, 2026');
for(const items of [topics,resources,paths])assert.equal(new Set(items.map(x=>x.id)).size,items.length,'IDs must be unique');
for(const resource of resources){assert(topics.some(t=>t.id===resource.topic));assert.notEqual(utils.sourceHref(resource.url),'#');assert(resource.title&&resource.description);}
for(const path of paths){assert.equal(path.steps.length,4);for(const step of path.steps)assert(resources.some(r=>r.id===step[0]),`Missing resource ${step[0]}`);}
for(const term of glossary)assert(topics.some(t=>t.id===term[2]));
const html=await readFile(join(root,'index.html'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate document IDs');
for(const match of html.matchAll(/(?:src|href)="(\.\/[^"?]+)(?:\?[^\"]*)?"/g))await access(join(root,match[1]));
const scripts=[...html.matchAll(/<script defer src="([^"?]+)/g)].map(m=>m[1]);
assert(scripts.indexOf('./dist/hub-utils.js')<scripts.indexOf('./dist/app.js'));
assert(scripts.indexOf('./dist/app.js')<scripts.indexOf('./dist/hub.js'));
assert(!html.includes('cdn.jsdelivr.net'),'Core rendering dependency must be local');
const jobs=JSON.parse(await readFile(join(root,'data/jobs.json'),'utf8'));
for(const job of jobs.jobs.filter(j=>j.source==='Curated'))assert.equal(job.postedAt,null,'Curated jobs must not have fabricated posting dates');
console.log(`Passed: escaping and URL boundaries, search and routes, dates, ${topics.length} topics, ${resources.length} resources, ${paths.length} learning paths, ${glossary.length} terms, script order, local assets, and curated job date integrity.`);
