interface ResearcherMilestone {
  year: number;
  title: string;
  detail: string;
  url?: string;
}

interface ResearcherTrail {
  id: string;
  name: string;
  institution: string;
  country: string;
  region: string;
  group: string;
  startYear: number;
  start: string;
  summary: string;
  techIds: string[];
  profileUrl: string;
  literatureUrl: string;
  milestones: ResearcherMilestone[];
}

type ResearcherSeed = [string,string,string,string,string,string,number,string,string,string[],string,ResearcherMilestone[]];

const researcherSeeds: ResearcherSeed[] = [
  ["gyorgy-buzsaki","György Buzsáki","NYU Grossman School of Medicine","United States","North America","record",1984,"Started from hippocampal electrophysiology and the timing relationships between population rhythms and single-neuron firing.","Linked oscillations, spikes and behavior across scales, and helped establish the interpretive framework for extracellular signals.",["eeg","lfp","spikesort"],"https://med.nyu.edu/faculty/gyorgy-buzsaki",[{year:2004,title:"Rhythms as an organizing principle",detail:"Synthesized how oscillations coordinate neuronal assemblies."},{year:2012,title:"Origins of extracellular fields",detail:"Connected EEG, ECoG, local fields and unit activity with biophysical generators."}]],
  ["christof-koch","Christof Koch","Allen Institute","United States","North America","compute",1982,"Entered neuroscience through biophysical and computational models of dendrites and cortical neurons after training in physics.","Bridged neuronal biophysics, extracellular-field theory, visual computation, consciousness and cell-census programs.",["lfp","cellatlas","digitaltwin"],"https://alleninstitute.org/person/christof-koch",[{year:1987,title:"Computational biophysics at Caltech",detail:"Built quantitative models of single neurons and cortical computation."},{year:2011,title:"Allen Institute cell-census scale",detail:"Joined a large open-science effort to classify mouse and human brain cell types."}]],
  ["tim-harris","Tim Harris","HHMI Janelia Research Campus","United States","North America","record",2008,"Moved from single-molecule instrumentation into neuroscience measurement technology at Janelia.","Led the cross-institutional engineering effort that produced Neuropixels probes and their open hardware ecosystem.",["silicon","neuropixels"],"https://www.janelia.org/people/tim-harris",[{year:2013,title:"Neuropixels collaboration begins",detail:"Coordinated CMOS probe design across Janelia, imec, UCL and Allen Institute."},{year:2017,title:"Neuropixels 1.0",detail:"Published a fully integrated silicon probe for hundreds of simultaneous neural recordings.",url:"https://www.nature.com/articles/nature24636"}]],
  ["kenneth-harris","Kenneth Harris","University College London","United Kingdom","Europe","compute",2000,"Began with mathematical approaches to neural coding, spike detection and large-scale ensemble recordings.","Co-developed high-density recording analysis, Kilosort and Neuropixels-based population neuroscience.",["neuropixels","spikesort","decoder"],"https://www.ucl.ac.uk/brain-sciences/cortexlab",[{year:2016,title:"Kilosort",detail:"Helped introduce GPU-accelerated template matching for dense extracellular recordings."},{year:2021,title:"Neuropixels 2.0",detail:"Advanced stable, chronic recordings and cross-session neuron tracking."}]],
  ["marius-pachitariu","Marius Pachitariu","University College London","United Kingdom","Europe","compute",2013,"Started by combining machine learning with visual-cortex population recordings and image representations.","Created the Kilosort family of spike-sorting methods and scalable tools for neural data.",["spikesort","neuropixels","decoder"],"https://www.ucl.ac.uk/brain-sciences/cortexlab",[{year:2016,title:"Kilosort",detail:"Introduced real-time GPU spike sorting for hundreds of channels."},{year:2024,title:"Kilosort 4",detail:"Extended drift tracking and sorting performance for modern high-density probes."}]],
  ["karel-svoboda","Karel Svoboda","HHMI Janelia Research Campus","United States","North America","record",1997,"Started by using two-photon microscopy to observe structural plasticity in living cortical dendrites.","Built optical methods and collaborative programs for circuit-level measurement and perturbation.",["twophoton","calcium","cellatlas"],"https://www.janelia.org/people/karel-svoboda",[{year:2002,title:"In-vivo spine dynamics",detail:"Tracked experience-dependent structural changes in intact cortex."},{year:2014,title:"GENIE and sensor development",detail:"Helped organize open genetically encoded indicator engineering."}]],
  ["loren-frank","Loren Frank","University of California, San Francisco","United States","North America","compute",2001,"Began by recording hippocampal ensembles during spatial behavior to study memory formation and replay.","Connected high-channel-count recording, memory circuits and open automated spike-sorting workflows.",["lfp","spikesort","decoder"],"https://physiology.ucsf.edu/frank",[{year:2004,title:"Hippocampal replay and memory",detail:"Used population recordings to reveal coordinated sequence reactivation."},{year:2017,title:"MountainSort",detail:"Co-developed a fully automated spike-sorting and validation pipeline."}]],
  ["euisik-yoon","Euisik Yoon","University of Michigan","United States","North America","record",2000,"Started in microelectromechanical systems and integrated microsensors before focusing on neural interfaces.","Developed high-density silicon probes, multifunctional microsystems and scalable neural recording hardware.",["silicon","neuropixels","icms"],"https://micl.engin.umich.edu/",[{year:2008,title:"Integrated neural microsystems",detail:"Combined electrodes, electronics and microfluidics on compact probes."},{year:2018,title:"High-channel-count probes",detail:"Advanced dense silicon-array architectures for circuit mapping."}]],
  ["michael-roukes","Michael Roukes","California Institute of Technology","United States","North America","record",1999,"Entered neurotechnology from nanomechanics and nanoscale sensing, asking how dense physical systems could read neural activity.","Led large-scale nanoelectronic and implantable-interface programs spanning sensors, packaging and translation.",["nanowire","silicon","neuromorphic"],"https://www.roukeslab.caltech.edu/",[{year:2009,title:"Neurotechnology systems programs",detail:"Connected nanosystems engineering with massively parallel brain interfaces."},{year:2017,title:"Integrated interface scaling",detail:"Pursued dense, manufacturable implant platforms under national neurotechnology initiatives."}]],
  ["shigeyoshi-fujisawa","Shigeyoshi Fujisawa","RIKEN Center for Brain Science","Japan","Asia","record",2008,"Started with multisite ensemble recordings of prefrontal and hippocampal circuits during behavior.","Advanced large-scale electrophysiology for circuit dynamics, memory and decision-making.",["lfp","silicon","neuropixels"],"https://www.riken.jp/en/research/labs/cbs/circuit_behav_phys/",[{year:2011,title:"Prefrontal ensemble organization",detail:"Mapped cell assemblies and timing relationships during working behavior."},{year:2019,title:"Large-scale circuit physiology",detail:"Expanded dense recording across interacting memory and decision circuits."}]],

  ["lan-luan","Lan Luan","Rice University","United States","North America","record",2015,"Moved from nanomaterials and flexible electronics into neural interfaces designed to mechanically match brain tissue.","Developed ultraflexible NET electrodes for long-lived recording and low-threshold stimulation.",["net","stimnet","neuralcode"],"https://luanlab.rice.edu/",[{year:2017,title:"Glial-scar-free NET",detail:"Reported ultraflexible probes with minimal chronic tissue response.",url:"https://www.science.org/doi/10.1126/sciadv.1601966"},{year:2022,title:"Thousands of neurons over months",detail:"Scaled NET recordings while tracking large neuronal populations."}]],
  ["chong-xie","Chong Xie","Rice University","United States","North America","record",2015,"Started by adapting macroporous and mesh nanoelectronics to reduce the mechanical mismatch between probes and brain tissue.","Built tissue-like neural electronics and scalable chronic interfaces.",["mesh","net","nanowire"],"https://xielab.rice.edu/",[{year:2015,title:"Mesh electronics injection",detail:"Demonstrated syringe-injectable electronics that integrate with tissue."},{year:2019,title:"Tissue-like neural probes",detail:"Advanced ultraflexible arrays for stable chronic electrophysiology."}]],
  ["charles-lieber","Charles Lieber","Harvard University","United States","North America","record",1998,"Began with semiconductor nanowires and their electrical properties before turning them into cellular probes.","Pioneered nanoscale transistor probes, mesh electronics and biointegrated neural interfaces.",["nanowire","mesh","organoid"],"https://cml.harvard.edu/people/charles-m-lieber",[{year:2010,title:"Nanowire cellular probes",detail:"Used kinked nanowire transistors for intracellular-like cellular recording."},{year:2015,title:"Injectable mesh electronics",detail:"Introduced macroporous electronics that unfold and integrate in brain tissue."}]],
  ["john-rogers","John A. Rogers","Northwestern University","United States","North America","record",2003,"Started by making high-performance electronics bend, stretch and conform to soft surfaces.","Translated soft materials into epidermal sensors, cortical arrays and transient bioelectronics.",["ecog","resorb","wearable"],"https://rogersgroup.northwestern.edu/",[{year:2010,title:"Conformal cortical electronics",detail:"Demonstrated flexible, high-density arrays that wrap curved brain surfaces."},{year:2016,title:"Bioresorbable brain sensors",detail:"Created temporary implants designed to dissolve after monitoring."}]],
  ["jonathan-viventi","Jonathan Viventi","Duke University","United States","North America","record",2011,"Started by integrating active electronics into flexible sheets for high-resolution cortical mapping.","Developed scalable, conformal ECoG arrays and translational systems for epilepsy and brain-machine interfaces.",["ecog","ecogflex","speechecog"],"https://viventi.pratt.duke.edu/",[{year:2011,title:"Active flexible ECoG",detail:"Reported multiplexed, conformal arrays for high-resolution brain activity mapping."},{year:2023,title:"Scalable cortical interfaces",detail:"Expanded channel density, packaging and human translational workflows."}]],
  ["george-malliaras","George Malliaras","University of Cambridge","United Kingdom","Europe","record",2009,"Entered bioelectronics through organic mixed ionic-electronic conductors that can translate biological ions into electronic signals.","Developed organic neural transistors, electrophoretic drug delivery and soft implant interfaces.",["ecogflex","neurotransmitter","resorb"],"https://bioelectronics.eng.cam.ac.uk/",[{year:2013,title:"Organic electrochemical neural transistors",detail:"Amplified neural signals directly at soft recording interfaces."},{year:2020,title:"Integrated bioelectronic therapy",detail:"Combined sensing, stimulation and local drug delivery in conformable platforms."}]],
  ["stephanie-lacour","Stéphanie Lacour","EPFL","Switzerland","Europe","restore",2004,"Started by engineering stretchable metal interconnects and soft electronic skins.","Applied compliant electronics to spinal implants, peripheral nerve interfaces and neuroprosthetic systems.",["ees","pni","ecogflex"],"https://lsbi.epfl.ch/",[{year:2015,title:"e-dura",detail:"Introduced a soft spinal implant that combined recording, stimulation and chemistry."},{year:2021,title:"Soft neuroprosthetic interfaces",detail:"Expanded stretchable systems for movement restoration and chronic biointegration."}]],
  ["cynthia-chestek","Cynthia Chestek","University of Michigan","United States","North America","restore",2009,"Started with intracortical motor decoding and the stability of neural population signals.","Builds implantable interfaces, peripheral-nerve systems and algorithms for dexterous prosthetic control.",["motorbci","pni","bionichand"],"https://chestekresearch.engin.umich.edu/",[{year:2012,title:"Stable intracortical control",detail:"Demonstrated long-duration decoding for cursor and robotic control."},{year:2020,title:"Peripheral nerve and regenerative interfaces",detail:"Expanded bidirectional control beyond the cortex."}]],
  ["takao-someya","Takao Someya","University of Tokyo","Japan","Asia","personal",2004,"Started with large-area organic transistor arrays and electronic skin.","Pioneered ultrathin, stretchable sensors that shaped wearable physiology and soft neural-interface design.",["wearable","fnirs","ecogflex"],"https://www.someya.t.u-tokyo.ac.jp/",[{year:2005,title:"Electronic skin",detail:"Integrated pressure sensors and organic electronics over flexible areas."},{year:2016,title:"Ultraflexible physiological sensors",detail:"Created skin-like platforms with very low mechanical burden."}]],
  ["polina-anikeeva","Polina Anikeeva","MIT","United States","North America","stimulate",2012,"Started by combining materials science, photonics and neural engineering in multifunctional fibers.","Created fiber probes and magnetic, optical and chemical approaches for distributed neural modulation.",["opto","magneto","neurotransmitter"],"https://anikeeva.mit.edu/",[{year:2015,title:"Wireless magnetothermal stimulation",detail:"Used magnetic nanoparticles to activate deep neural circuits without tethered optics."},{year:2017,title:"Multifunctional neural fibers",detail:"Integrated recording, optical stimulation and drug delivery in one flexible probe."}]],

  ["john-donoghue","John Donoghue","Brown University","United States","North America","restore",1992,"Started by studying how motor cortex populations encode arm movement.","Founded BrainGate and helped translate intracortical population decoding into human assistive control.",["utah","motorbci","bionichand"],"https://vivo.brown.edu/display/jdonoghu",[{year:2004,title:"BrainGate human trial",detail:"Launched implanted cortical control studies in people with paralysis."},{year:2006,title:"Human cursor and device control",detail:"Reported direct control of external devices from motor-cortex activity."}]],
  ["leigh-hochberg","Leigh Hochberg","Brown University / Massachusetts General Hospital","United States","North America","restore",2006,"Began at the intersection of vascular neurology, critical care and the first BrainGate clinical studies.","Leads long-running intracortical BCI trials for communication and movement restoration.",["utah","motorbci","speechspike"],"https://vivo.brown.edu/display/lhochber",[{year:2012,title:"Robotic-arm control",detail:"Enabled people with tetraplegia to reach and grasp using intracortical signals."},{year:2021,title:"Rapid communication BCIs",detail:"Advanced high-performance typing and speech-related interfaces."}]],
  ["krishna-shenoy","Krishna Shenoy","Stanford University","United States","North America","compute",2000,"Started by studying motor-cortex population dynamics with computational and electrophysiological tools.","Established dynamical-systems approaches to motor control and high-performance intracortical BCIs.",["motorbci","decoder","neuralcode"],"https://shenoy.people.stanford.edu/",[{year:2012,title:"Neural population dynamics",detail:"Reframed motor-cortex activity as an evolving dynamical system."},{year:2017,title:"High-performance typing",detail:"Combined stable decoding and point-and-click control for people with paralysis."}]],
  ["jaimie-henderson","Jaimie Henderson","Stanford University","United States","North America","restore",2004,"Started as a functional neurosurgeon implanting cortical arrays for human motor-interface research.","Connects neurosurgery, BrainGate trials and speech/handwriting neuroprostheses.",["utah","handwriting","speechspike"],"https://profiles.stanford.edu/jaimie-henderson",[{year:2021,title:"Handwriting BCI",detail:"Helped translate attempted handwriting into rapid text."},{year:2023,title:"Speech neuroprosthesis",detail:"Supported high-vocabulary decoding from intracortical activity."}]],
  ["frank-willett","Frank Willett","Stanford University","United States","North America","compute",2017,"Started by decoding attempted arm and hand movements from motor-cortex population activity.","Led handwriting and speech decoding systems that turned intracortical signals into fast communication.",["motorbci","handwriting","speechspike"],"https://profiles.stanford.edu/frank-willett",[{year:2021,title:"Handwriting-to-text",detail:"Decoded attempted handwriting at communication-relevant rates."},{year:2023,title:"Large-vocabulary speech",detail:"Decoded words and sentences from motor-cortex speech activity."}]],
  ["edward-chang","Edward Chang","University of California, San Francisco","United States","North America","restore",2010,"Started by mapping human speech and language cortex with high-density ECoG during neurosurgery.","Leads BRAVO studies translating cortical speech representations into text, audio and avatar control.",["ecog","speechecog","corticalstim"],"https://changlab.ucsf.edu/",[{year:2019,title:"Synthesized speech from cortex",detail:"Reconstructed intelligible speech using decoded articulatory representations."},{year:2023,title:"Speech-and-avatar neuroprosthesis",detail:"Combined text, audible speech and facial animation from cortical activity."}]],
  ["gopala-anumanchipalli","Gopala Anumanchipalli","University of California, Berkeley","United States","North America","compute",2012,"Started in speech science and statistical models of articulation and acoustics.","Bridges speech production models, machine learning and cortical decoding for communication neuroprostheses.",["speechecog","decoder","neuralcode"],"https://spherelab.berkeley.edu/",[{year:2019,title:"Neural speech synthesis",detail:"Mapped cortical activity through an articulatory intermediate to reconstruct speech."},{year:2023,title:"Generalizable speech decoding",detail:"Advanced high-vocabulary, multimodal speech neuroprostheses."}]],
  ["nick-ramsey","Nick Ramsey","UMC Utrecht","Netherlands","Europe","restore",2003,"Started by combining human functional imaging and intracranial recordings to identify signals for communication.","Developed fully implanted communication BCIs and long-term home-use protocols.",["ecog","motorbci","speechecog"],"https://www.nick-ramsey.eu/",[{year:2016,title:"Home-use implanted BCI",detail:"Demonstrated independent communication with a fully implanted ECoG system."},{year:2023,title:"Long-term implant studies",detail:"Expanded participant-centered communication and signal-stability research."}]],
  ["jose-millan","José del R. Millán","University of Texas at Austin","United States","North America","compute",2004,"Started with adaptive machine learning for non-invasive EEG brain-computer interfaces.","Pioneered shared control, error-related potentials and human-robot BCI interaction.",["eeg","motorbci","decoder"],"https://sites.utexas.edu/jose-del-r-millan/",[{year:2008,title:"Shared-control BCI",detail:"Combined noisy neural intent with autonomous assistance for robust control."},{year:2018,title:"Clinical and wearable translation",detail:"Extended non-invasive BCIs toward rehabilitation and daily use."}]],
  ["miguel-nicolelis","Miguel Nicolelis","Duke University","United States","North America","restore",1999,"Started by recording large ensembles of cortical neurons during natural movement.","Demonstrated real-time brain-machine control, bilateral interfaces and locomotion-focused neurorehabilitation.",["motorbci","brainspine","bionichand"],"https://nicolelislab.net/",[{year:2003,title:"Real-time robotic control",detail:"Used distributed cortical ensembles to control a robotic arm."},{year:2014,title:"Walk Again Project",detail:"Combined BCI, robotics and sensory feedback for locomotor demonstrations."}]],

  ["richard-andersen","Richard Andersen","California Institute of Technology","United States","North America","compute",1996,"Started by revealing intention and reach planning signals in posterior parietal cortex.","Translated cognitive planning signals into BCIs for reach, grasp and communication.",["motorbci","decoder","sensorybci"],"https://www.vis.caltech.edu/",[{year:2015,title:"Posterior parietal BCI",detail:"Enabled a person with tetraplegia to control a robotic limb using high-level intentions."},{year:2022,title:"Cognitive neural prostheses",detail:"Expanded decoding of goals, imagined actions and abstract choices."}]],
  ["andrew-schwartz","Andrew Schwartz","University of Pittsburgh","United States","North America","restore",1988,"Started by describing population-vector representations of arm movement in motor cortex.","Led intracortical control of dexterous robotic arms and bidirectional motor-sensory systems.",["motorbci","bionichand","sensorybci"],"https://www.cnup.pitt.edu/people/andrew-schwartz-phd",[{year:2008,title:"High-dimensional robotic control",detail:"Demonstrated naturalistic reach and grasp from cortical activity."},{year:2012,title:"Human robotic-arm reach and grasp",detail:"Enabled a participant with tetraplegia to perform coordinated 3D movements."}]],
  ["sliman-bensmaia","Sliman Bensmaia","University of Chicago","United States","North America","restore",2007,"Started by quantifying how tactile features are encoded in peripheral nerves and somatosensory cortex.","Established biomimetic sensory feedback principles for intracortical neuroprostheses.",["icms","sensorybci","bionichand"],"https://bensmaialab.org/",[{year:2013,title:"ICMS-evoked touch",detail:"Mapped artificial tactile percepts produced by cortical microstimulation."},{year:2021,title:"Biomimetic feedback",detail:"Designed stimulation patterns that reproduce natural temporal and spatial touch codes."}]],
  ["robert-gaunt","Robert Gaunt","University of Pittsburgh","United States","North America","restore",2010,"Started with sensorimotor neurophysiology and peripheral/cortical stimulation for restoring function.","Co-led human bidirectional BCI systems that return touch through somatosensory cortex.",["icms","sensorybci","bionichand"],"https://www.rnel.pitt.edu/people/robert-gaunt",[{year:2016,title:"Human cortical touch",detail:"Enabled a person with tetraplegia to feel robotic-hand contact through ICMS."},{year:2021,title:"Bidirectional arm control",detail:"Integrated motor decoding and patterned sensory feedback."}]],
  ["lee-fisher","Lee Fisher","University of Pittsburgh","United States","North America","restore",2012,"Started with peripheral and spinal sensorimotor interfaces for movement and sensation.","Develops nerve stimulation, spinal stimulation and closed-loop systems for mobility and pain.",["pni","ees","tscs"],"https://www.rnel.pitt.edu/people/lee-fisher",[{year:2018,title:"Spinal sensorimotor interfaces",detail:"Linked targeted stimulation with functional movement and sensory pathways."},{year:2022,title:"Closed-loop peripheral systems",detail:"Combined neural sensing, stimulation and rehabilitation."}]],
  ["jennifer-collinger","Jennifer Collinger","University of Pittsburgh","United States","North America","restore",2008,"Started in rehabilitation engineering and human intracortical BCI trials.","Led participant-centered robotic-arm control and bidirectional BCI studies.",["motorbci","bionichand","sensorybci"],"https://www.rnel.pitt.edu/people/jennifer-collinger",[{year:2013,title:"Seven-dimensional arm control",detail:"Demonstrated coordinated reach, orientation and grasp in a person with tetraplegia."},{year:2021,title:"Motor plus sensory BCI",detail:"Integrated dexterous control with cortical tactile feedback."}]],
  ["dustin-tyler","Dustin Tyler","Case Western Reserve University","United States","North America","restore",2003,"Started with selective peripheral-nerve electrodes and stimulation models.","Translated implanted nerve cuffs into long-term sensory restoration and motor control.",["pni","bionichand","fes"],"https://engineering.case.edu/groups/nrc",[{year:2014,title:"Restored hand sensation",detail:"Delivered stable, graded tactile percepts through implanted nerve cuffs."},{year:2020,title:"Home neuroprosthesis use",detail:"Extended bidirectional prosthetic systems beyond supervised laboratory sessions."}]],
  ["silvestro-micera","Silvestro Micera","EPFL / Scuola Superiore Sant'Anna","Switzerland","Europe","restore",2008,"Started with neural control of robotic and prosthetic limbs using peripheral nerve signals.","Advanced bidirectional hand prostheses, intraneural electrodes and sensory feedback.",["pni","bionichand","sensorybci"],"https://www.epfl.ch/labs/tne/",[{year:2014,title:"Real-time sensory hand",detail:"Returned touch information through intraneural stimulation during prosthetic use."},{year:2019,title:"Multimodal bionic feedback",detail:"Combined tactile and position information for more natural control."}]],
  ["stanisa-raspopovic","Stanisa Raspopovic","ETH Zürich","Switzerland","Europe","restore",2014,"Started with computationally guided intraneural stimulation for sensory hand prostheses.","Develops selective nerve interfaces and closed-loop neuroprostheses for limbs and internal organs.",["pni","bionichand","sensorybci"],"https://nuro.ethz.ch/",[{year:2014,title:"Sensory feedback through TIME electrodes",detail:"Helped restore real-time touch during grasping."},{year:2019,title:"Leg neuroprosthesis feedback",detail:"Extended sensory restoration to lower-limb prostheses and gait."}]],
  ["max-ortiz-catalan","Max Ortiz-Catalan","Bionics Institute","Australia","Oceania","restore",2014,"Started by tightly integrating bone anchoring, muscle electrodes and nerve interfaces for prosthetic control.","Developed neuromusculoskeletal prostheses and long-term take-home bionic systems.",["pni","bionichand","emg"],"https://www.bionicsinstitute.org/",[{year:2020,title:"Daily-life neuromusculoskeletal prosthesis",detail:"Reported stable control and sensation through implanted interfaces."},{year:2023,title:"Bionic reconstruction and phantom-pain work",detail:"Expanded implanted systems toward clinical rehabilitation."}]],

  ["andres-lozano","Andres Lozano","University of Toronto","Canada","North America","stimulate",1998,"Started as a functional neurosurgeon studying basal-ganglia circuits and deep-brain stimulation for movement disorders.","Expanded DBS toward depression, Alzheimer disease and circuit-guided therapy.",["dbs","adbs","cldepression"],"https://lozanolab.utoronto.ca/",[{year:2005,title:"Circuit targets beyond movement",detail:"Helped open DBS research for severe psychiatric and cognitive disorders."},{year:2016,title:"Network-guided DBS",detail:"Connected imaging, physiology and long-term clinical programming."}]],
  ["helen-mayberg","Helen Mayberg","Icahn School of Medicine at Mount Sinai","United States","North America","stimulate",1997,"Started by mapping distributed brain-network changes in depression and treatment response with functional imaging.","Defined a depression circuit framework and pioneered subcallosal-cingulate DBS.",["fmri","dbs","cldepression"],"https://labs.icahn.mssm.edu/mayberglab/",[{year:2005,title:"DBS for treatment-resistant depression",detail:"Reported early clinical effects of subcallosal-cingulate stimulation."},{year:2021,title:"Personalized circuit biomarkers",detail:"Integrated imaging, electrophysiology and behavioral state tracking."}]],
  ["philip-starr","Philip Starr","University of California, San Francisco","United States","North America","stimulate",1998,"Started in movement-disorder surgery and the physiology of basal-ganglia circuits during DBS procedures.","Pioneered chronic cortical sensing and adaptive stimulation for Parkinson disease.",["dbs","adbs","ecog"],"https://star-lab.ucsf.edu/",[{year:2013,title:"Chronic cortical sensing with DBS",detail:"Combined implanted stimulation with long-term ECoG recording."},{year:2021,title:"Adaptive DBS in daily life",detail:"Advanced biomarker-triggered stimulation outside the laboratory."}]],
  ["timothy-denison","Timothy Denison","University of Oxford","United Kingdom","Europe","stimulate",2007,"Started in industry building implantable sensing and stimulation circuits for chronic neurological therapy.","Bridges low-power implant engineering, control theory and translational neuromodulation.",["dbs","adbs","rns"],"https://www.ibme.ox.ac.uk/research/non-invasive-therapy-drug-delivery/neuromodulation-group",[{year:2015,title:"Sensing-enabled implants",detail:"Helped establish bidirectional platforms that record biomarkers while stimulating."},{year:2020,title:"Academic-industry open translation",detail:"Expanded adaptive therapy methods and reproducible implant research."}]],
  ["peter-brown","Peter Brown","University of Oxford","United Kingdom","Europe","compute",2001,"Started by identifying pathological beta-band synchronization in Parkinsonian basal-ganglia networks.","Connected oscillation biomarkers to adaptive DBS and closed-loop motor therapy.",["lfp","dbs","adbs"],"https://www.ndcn.ox.ac.uk/team/peter-brown",[{year:2013,title:"Beta-guided adaptive DBS",detail:"Demonstrated stimulation triggered by a disease-linked neural rhythm."},{year:2020,title:"Movement-state decoding",detail:"Extended closed-loop biomarkers toward natural behavior."}]],
  ["warren-grill","Warren Grill","Duke University","United States","North America","stimulate",1995,"Started with biophysical models of how electrical stimulation recruits axons and neural populations.","Develops mechanisms, electrode designs and control strategies for DBS, spinal and peripheral stimulation.",["dbs","ees","pni"],"https://grill-lab.pratt.duke.edu/",[{year:2005,title:"Mechanistic stimulation models",detail:"Linked waveform and electrode geometry to neural-element recruitment."},{year:2013,title:"Principles of neural stimulation",detail:"Synthesized design rules for selective, safe and effective neuromodulation."}]],
  ["cameron-mcintyre","Cameron McIntyre","Case Western Reserve University","United States","North America","compute",2002,"Started with computational models of the volume of tissue activated by DBS.","Built patient-specific field models and software for interpreting and planning stimulation.",["dbs","digitaltwin","adbs"],"https://engineering.case.edu/groups/mcintyrelab/",[{year:2007,title:"DBS pathway activation models",detail:"Connected electric fields to axonal recruitment and therapeutic pathways."},{year:2015,title:"Patient-specific stimulation maps",detail:"Integrated imaging, lead location and biophysical simulation."}]],
  ["alim-louis-benabid","Alim-Louis Benabid","Clinatec / Grenoble Alpes University","France","Europe","stimulate",1987,"Started from stereotactic neurosurgery and discovered that high-frequency thalamic stimulation could suppress tremor.","Established modern high-frequency DBS and helped build a translational neurotechnology center.",["dbs","adbs","motorbci"],"https://www.clinatec.fr/en/",[{year:1993,title:"Subthalamic DBS",detail:"Extended chronic stimulation to Parkinson disease motor symptoms."},{year:2012,title:"Clinatec translation",detail:"Linked devices, imaging, robotics and clinical trials under one program."}]],
  ["gregoire-courtine","Grégoire Courtine","EPFL / NeuroRestore","Switzerland","Europe","restore",2009,"Started by studying spinal locomotor circuits and activity-dependent recovery after spinal-cord injury.","Developed spatiotemporal spinal stimulation and brain-spine interfaces for walking.",["ees","brainspine","tscs"],"https://www.neurorestore.swiss/",[{year:2018,title:"Targeted epidural stimulation",detail:"Restored overground walking in selected people with chronic spinal injury."},{year:2023,title:"Brain-spine interface",detail:"Linked cortical intent to gait-phase spinal stimulation."}]],
  ["jocelyne-bloch","Jocelyne Bloch","CHUV / NeuroRestore","Switzerland","Europe","restore",2010,"Started as a functional neurosurgeon translating cell and stimulation therapies for severe neurological injury.","Leads implantation and clinical protocols for spinal stimulation and brain-spine interfaces.",["ees","brainspine","cellreplacement"],"https://www.neurorestore.swiss/",[{year:2018,title:"Clinical spinal-interface implantation",detail:"Co-led targeted stimulation procedures for walking recovery."},{year:2023,title:"Wireless brain-spine bridge",detail:"Implemented cortical and spinal implants for real-time locomotor control."}]],

  ["karl-deisseroth","Karl Deisseroth","Stanford University","United States","North America","stimulate",2005,"Started by combining microbial opsins, viral gene delivery and optical fibers to control defined neurons.","Established optogenetics and later tissue-clearing and activity-imaging methods.",["opto","clearing","calcium"],"https://dlab.stanford.edu/",[{year:2005,title:"Millisecond optogenetic control",detail:"Demonstrated light-driven spiking in genetically targeted mammalian neurons."},{year:2013,title:"CLARITY",detail:"Made intact tissue optically transparent while preserving molecular structure."}]],
  ["ed-boyden","Ed Boyden","MIT","United States","North America","stimulate",2005,"Started by co-developing the first widely used single-component optogenetic control in neurons.","Expanded neural tools through new opsins, expansion microscopy and high-throughput technology design.",["opto","clearing","voltage"],"https://syntheticneurobiology.org/",[{year:2010,title:"Optogenetic silencing tools",detail:"Extended optical control across colors, kinetics and inhibitory mechanisms."},{year:2015,title:"Expansion microscopy",detail:"Physically enlarged tissue to enable nanoscale imaging with ordinary microscopes."}]],
  ["peter-hegemann","Peter Hegemann","Humboldt University of Berlin","Germany","Europe","stimulate",2002,"Started from algal phototaxis and the molecular identity of channelrhodopsins.","Characterized light-gated channels that became core optogenetic actuators.",["opto","voltage"],"https://www.biologie.hu-berlin.de/en/gruppenseiten/expbp",[{year:2003,title:"Channelrhodopsin as a light-gated channel",detail:"Established the molecular mechanism enabling direct optical depolarization."},{year:2014,title:"Engineered opsin palette",detail:"Improved spectral range, kinetics and photocurrent for circuit control."}]],
  ["georg-nagel","Georg Nagel","University of Würzburg","Germany","Europe","stimulate",2003,"Started by expressing and characterizing microbial channelrhodopsins as directly light-gated ion channels.","Provided the actuator foundation for modern optogenetic excitation.",["opto","voltage"],"https://www.biozentrum.uni-wuerzburg.de/biophys/",[{year:2005,title:"Neuronal channelrhodopsin control",detail:"Helped demonstrate reliable light-driven firing in excitable cells."},{year:2015,title:"New photoreceptors and signaling tools",detail:"Expanded optogenetic control beyond classical cation channels."}]],
  ["gero-miesenbock","Gero Miesenböck","University of Oxford","United Kingdom","Europe","stimulate",2002,"Started by genetically encoding optical control components to remotely activate selected neurons.","Pioneered optogenetic circuit interrogation and causal behavioral experiments.",["opto","neuralcode"],"https://cncb.ox.ac.uk/",[{year:2005,title:"Remote control of fly behavior",detail:"Used genetically targeted photostimulation to trigger defined actions."},{year:2010,title:"Causal circuit dissection",detail:"Applied optical control to identify neural mechanisms of learning and action."}]],
  ["bryan-roth","Bryan Roth","University of North Carolina at Chapel Hill","United States","North America","stimulate",1998,"Started from receptor pharmacology and the structure-function relationships of G-protein-coupled receptors.","Created DREADD chemogenetic actuators and receptor-based neuropsychiatric tools.",["chemo","neurotransmitter"],"https://rothlab.org/",[{year:2007,title:"DREADDs",detail:"Introduced engineered receptors activated by otherwise inert ligands."},{year:2014,title:"Chemogenetic toolkit expansion",detail:"Improved actuators, ligands and cell-type-specific circuit applications."}]],
  ["scott-sternson","Scott Sternson","HHMI Janelia Research Campus","United States","North America","stimulate",2005,"Started with molecular and genetic methods for identifying hypothalamic circuits controlling behavior.","Uses optogenetic, chemogenetic and anatomical tools to map motivational and homeostatic systems.",["opto","chemo","cellatlas"],"https://www.janelia.org/lab/sternson-lab",[{year:2013,title:"Hunger-circuit control",detail:"Resolved opposing genetically defined neurons that drive and suppress feeding."},{year:2017,title:"Projection-defined circuit logic",detail:"Mapped how cell types and pathways assemble motivational states."}]],
  ["guoping-feng","Guoping Feng","MIT McGovern Institute","United States","North America","stimulate",1999,"Started by engineering mouse genetics to connect synaptic molecules with circuit function and behavior.","Builds disease models and circuit interventions spanning optogenetics, gene editing and neuromodulation.",["opto","chemo","cellreplacement"],"https://mcgovern.mit.edu/profile/guoping-feng/",[{year:2007,title:"Circuit models of neuropsychiatric disease",detail:"Linked defined synaptic disruptions to repetitive and social behaviors."},{year:2017,title:"Precision circuit intervention",detail:"Combined genetic models with targeted recording and modulation."}]],
  ["viviana-gradinaru","Viviana Gradinaru","California Institute of Technology","United States","North America","stimulate",2009,"Started by engineering opsins and optical strategies for dissecting long-range neural projections.","Developed tissue clearing, systemic viral vectors and minimally invasive access to distributed circuits.",["opto","clearing","fusbbb"],"https://gradinaru.caltech.edu/",[{year:2013,title:"Whole-body and brain clearing",detail:"Advanced transparent-tissue methods for intact circuit mapping."},{year:2016,title:"Systemic AAV delivery",detail:"Engineered viral vectors that cross biological barriers for broad nervous-system access."}]],
  ["bernardo-sabatini","Bernardo Sabatini","Harvard Medical School","United States","North America","record",1999,"Started by using two-photon glutamate uncaging and imaging to quantify individual synapses.","Connects synaptic physiology, optical tools and basal-ganglia circuit mechanisms.",["twophoton","calcium","opto"],"https://sabatini.hms.harvard.edu/",[{year:2002,title:"Single-spine physiology",detail:"Measured calcium and plasticity at identified dendritic spines."},{year:2016,title:"Cell-type-specific circuit mapping",detail:"Combined optical control and imaging to resolve basal-ganglia pathways."}]],

  ["winfried-denk","Winfried Denk","Max Planck Institute","Germany","Europe","record",1990,"Started by co-inventing two-photon laser-scanning microscopy for deep imaging in living tissue.","Also pioneered serial block-face electron microscopy, linking functional imaging and connectomics.",["twophoton","connectome","calcium"],"https://www.neuro.mpg.de/denk",[{year:2004,title:"Serial block-face EM",detail:"Automated acquisition of three-dimensional ultrastructure for circuit reconstruction."},{year:2012,title:"Cross-scale circuit imaging",detail:"Integrated optical physiology and nanometer anatomy as complementary approaches."}]],
  ["atsushi-miyawaki","Atsushi Miyawaki","RIKEN Center for Brain Science","Japan","Asia","record",1997,"Started by engineering fluorescent protein sensors for calcium and intracellular signaling.","Created indicator families and multicolor tools for live-cell and whole-brain imaging.",["calcium","voltage","clearing"],"https://www.riken.jp/en/research/labs/cbs/cell_func_dyn/",[{year:2001,title:"Cameleon sensors mature",detail:"Improved genetically encoded calcium measurements in living cells."},{year:2013,title:"Bright multicolor indicators",detail:"Expanded temporal and spectral access to cellular activity."}]],
  ["loren-looger","Loren Looger","HHMI Janelia Research Campus","United States","North America","record",2009,"Started from computational protein design and turned engineered binding proteins into neural activity sensors.","Led development of high-performance GCaMP calcium indicators and neurotransmitter sensors.",["calcium","neurotransmitter","voltage"],"https://www.janelia.org/people/loren-looger",[{year:2013,title:"GCaMP6",detail:"Produced sensitive, fast calcium indicators for large-scale in-vivo imaging."},{year:2018,title:"Genetically encoded transmitter sensors",detail:"Expanded optical measurement from spikes to chemical signaling."}]],
  ["na-ji","Na Ji","University of California, Berkeley","United States","North America","record",2008,"Started by applying adaptive optics to correct tissue-induced aberrations in microscopy.","Develops deep, fast and minimally invasive imaging of neural activity in behaving animals.",["twophoton","calcium","mesoscope"],"https://www.jilab.net/",[{year:2012,title:"Adaptive-optics two-photon imaging",detail:"Recovered cellular resolution at depths where scattering and aberration blur signals."},{year:2020,title:"Deep functional imaging",detail:"Combined wavefront correction and advanced excitation for intact-brain measurements."}]],
  ["alipasha-vaziri","Alipasha Vaziri","Rockefeller University","United States","North America","record",2012,"Started by adapting light-field and computational microscopy for rapid volumetric neural imaging.","Built high-speed three-dimensional platforms for whole-brain and cortical population dynamics.",["calcium","mesoscope","digitaltwin"],"https://www.vazirilab.org/",[{year:2014,title:"Whole-brain light-field imaging",detail:"Recorded distributed neural activity in freely moving small organisms."},{year:2021,title:"High-speed volumetric cortex imaging",detail:"Scaled computational microscopy to large mammalian populations."}]],
  ["adam-cohen","Adam Cohen","Harvard University","United States","North America","record",2009,"Started by engineering fluorescent voltage indicators and optical electrophysiology methods.","Develops all-optical approaches that read and perturb fast membrane-voltage dynamics.",["voltage","opto","neuralcode"],"https://cohenweb.rc.fas.harvard.edu/",[{year:2018,title:"Kilohertz voltage imaging",detail:"Tracked spikes and subthreshold activity optically across cell populations."},{year:2022,title:"All-optical electrophysiology",detail:"Combined voltage reporters and optogenetic actuators for closed-loop circuit tests."}]],
  ["fritjof-helmchen","Fritjof Helmchen","University of Zurich","Switzerland","Europe","record",1999,"Started with in-vivo two-photon calcium imaging of neuronal dendrites and populations.","Expanded multiphoton microscopy across cortical layers, regions and behaving animals.",["twophoton","calcium","mesoscope"],"https://www.hifo.uzh.ch/en/research/helmchen.html",[{year:2013,title:"Miniaturized and deep imaging",detail:"Advanced optical access to distributed circuits during behavior."},{year:2020,title:"Multi-area cortical dynamics",detail:"Linked local cellular measurements with brain-wide function."}]],
  ["david-tank","David Tank","Princeton University","United States","North America","record",1988,"Started with optical measurements of membrane voltage and population activity in neural tissue.","Connected virtual behavior, two-photon imaging and quantitative models of navigation circuits.",["voltage","calcium","digitaltwin"],"https://pni.princeton.edu/people/david-tank",[{year:2010,title:"Virtual-reality navigation imaging",detail:"Recorded hippocampal and cortical neurons while animals navigated controlled environments."},{year:2018,title:"Population dynamics across behavior",detail:"Integrated optical data and circuit models of decision and navigation."}]],
  ["rafael-yuste","Rafael Yuste","Columbia University","United States","North America","record",1992,"Started by using calcium imaging to observe coordinated activity across cortical neuron populations.","Advanced optical circuit interrogation and helped articulate the vision that became the U.S. BRAIN Initiative.",["calcium","opto","neuroethics"],"https://yustelab.org/",[{year:2012,title:"Brain activity map proposal",detail:"Co-developed a large-scale vision for recording and manipulating complete neural circuits."},{year:2017,title:"Neurorights advocacy",detail:"Connected emerging neurotechnology capabilities to rights and governance questions."}]],
  ["mark-schnitzer","Mark Schnitzer","Stanford University","United States","North America","record",2003,"Started by miniaturizing two-photon and microendoscopic imaging for deep and freely behaving preparations.","Developed cellular-resolution microscopes and analysis for long-term population tracking.",["miniscope","calcium","mesoscope"],"https://pyramidal.stanford.edu/",[{year:2011,title:"Head-mounted cellular imaging",detail:"Enabled large neural-population recordings during natural behavior."},{year:2018,title:"Longitudinal ensemble tracking",detail:"Followed identified neurons across learning and disease progression."}]],

  ["jeff-lichtman","Jeff Lichtman","Harvard University","United States","North America","record",1987,"Started by tracing neuromuscular connections and how synapses compete and remodel during development.","Pioneered Brainbow labeling and large-volume electron-microscopy connectomics.",["connectome","clearing","cellatlas"],"https://lichtmanlab.fas.harvard.edu/",[{year:2007,title:"Brainbow",detail:"Used combinatorial fluorescent labeling to distinguish densely interwoven neurons."},{year:2024,title:"Human cortical EM volume",detail:"Co-led petascale reconstruction of a cubic millimeter of human cortex."}]],
  ["sebastian-seung","Sebastian Seung","Princeton University","United States","North America","compute",2009,"Started connectomics by applying machine learning and graph ideas to reconstruct wiring from electron microscopy.","Popularized scalable connectome analysis and citizen-science proofreading.",["connectome","decoder","digitaltwin"],"https://seunglab.org/",[{year:2012,title:"EyeWire",detail:"Turned retinal neuron reconstruction into a large collaborative online project."},{year:2018,title:"Dense circuit reconstruction",detail:"Connected automated segmentation with biological circuit analysis."}]],
  ["viren-jain","Viren Jain","Google Research","United States","North America","compute",2007,"Started by applying machine learning to membrane detection and neuron segmentation in electron micrographs.","Led flood-filling and large-scale reconstruction systems for mammalian and insect connectomes.",["connectome","decoder","digitaltwin"],"https://research.google/people/virenjain/",[{year:2017,title:"Flood-filling networks",detail:"Greatly reduced merge errors in automated neural segmentation."},{year:2024,title:"Petascale human-cortex reconstruction",detail:"Combined AI segmentation with open visualization of dense human tissue."}]],
  ["clay-reid","R. Clay Reid","Allen Institute","United States","North America","record",1995,"Started with visual-cortex physiology and the organization of receptive fields and local circuits.","Integrated functional recordings, anatomy and large-scale observatory programs.",["calcium","connectome","cellatlas"],"https://alleninstitute.org/person/r-clay-reid/",[{year:2012,title:"Allen Institute circuit programs",detail:"Joined team-science projects mapping cell types, connectivity and function."},{year:2021,title:"MICrONS",detail:"Connected two-photon responses with dense electron-microscopy wiring."}]],
  ["moritz-helmstaedter","Moritz Helmstaedter","Max Planck Institute for Brain Research","Germany","Europe","compute",2013,"Started by scaling electron-microscopy reconstruction and crowd-assisted annotation of cortical circuits.","Builds dense mammalian connectomes and quantitative theories of circuit structure.",["connectome","cellatlas","digitaltwin"],"https://brain.mpg.de/research/helmstaedter-department.html",[{year:2015,title:"Dense cortical connectomics",detail:"Mapped inhibitory and excitatory wiring in mammalian tissue."},{year:2024,title:"Larger mammalian circuit volumes",detail:"Expanded automation, proofreading and comparative connectomics."}]],
  ["hanchuan-peng","Hanchuan Peng","Southeast University","China","Asia","compute",2010,"Started by creating Vaa3D for three-dimensional visualization and automated tracing of large microscopy datasets.","Led open neuron-reconstruction platforms and the BigNeuron benchmarking collaboration.",["cellatlas","clearing","digitaltwin"],"https://penglab.com/",[{year:2015,title:"BigNeuron",detail:"Organized community benchmarking of automated neuron-tracing algorithms."},{year:2021,title:"Whole-brain morphology atlases",detail:"Scaled reconstruction and registration across large neuronal collections."}]],
  ["hongkui-zeng","Hongkui Zeng","Allen Institute","United States","North America","record",2002,"Started by building genetic and anatomical tools for mapping mouse brain cell populations.","Leads multimodal cell-type atlases, connectivity maps and open brain-science resources.",["cellatlas","patchseq","spatialomics"],"https://alleninstitute.org/person/hongkui-zeng/",[{year:2015,title:"Cell Types Database",detail:"Released integrated morphology, physiology and transcriptomic cell data."},{year:2021,title:"BICCN motor-cortex census",detail:"Helped coordinate cross-species multimodal cell classification."}]],
  ["ed-lein","Ed Lein","Allen Institute","United States","North America","record",2007,"Started by building the Allen Human Brain Atlas and spatial gene-expression resources.","Maps molecular and cellular organization across species using transcriptomics and spatial methods.",["cellatlas","spatialomics","patchseq"],"https://alleninstitute.org/person/ed-lein/",[{year:2012,title:"Human Brain Atlas",detail:"Released anatomically registered gene-expression maps of the adult human brain."},{year:2023,title:"Cross-species cell atlases",detail:"Integrated single-cell and spatial data from mouse, primate and human cortex."}]],
  ["john-ngai","John Ngai","NIH BRAIN Initiative","United States","North America","record",1996,"Started by studying olfactory receptor expression and sensory-neuron development.","Later led national cell-census and neurotechnology programs as director of the NIH BRAIN Initiative.",["cellatlas","spatialomics","neuroethics"],"https://braininitiative.nih.gov/about/leadership",[{year:2017,title:"BICCN launch",detail:"Helped organize systematic cell-type census work across technologies and species."},{year:2020,title:"BRAIN Initiative director",detail:"Began coordinating the next phase of U.S. neurotechnology investment."}]],
  ["aviv-regev","Aviv Regev","Genentech / Human Cell Atlas","United States","North America","compute",2011,"Started by applying computational genomics to distinguish cellular states and regulatory programs at single-cell resolution.","Co-founded the Human Cell Atlas and influenced brain-cell census and spatial-omics strategies.",["cellatlas","spatialomics","digitaltwin"],"https://www.gene.com/scientists/our-scientists/aviv-regev",[{year:2017,title:"Human Cell Atlas",detail:"Co-launched an international effort to map human cell types with open standards."},{year:2020,title:"Multimodal and spatial cell maps",detail:"Expanded census work beyond RNA into perturbation and tissue context."}]],

  ["matteo-carandini","Matteo Carandini","University College London","United Kingdom","Europe","compute",1997,"Started by quantifying visual-cortex responses and normalization as a canonical neural computation.","Combines Neuropixels, imaging, behavior and theory to study distributed decision circuits.",["neuropixels","decoder","neuralcode"],"https://www.ucl.ac.uk/brain-sciences/cortexlab",[{year:2019,title:"International Brain Laboratory",detail:"Helped standardize behavior and Neuropixels recordings across laboratories."},{year:2022,title:"Brain-wide decision dynamics",detail:"Mapped sensory, internal-state and movement signals across many regions."}]],
  ["liam-paninski","Liam Paninski","Columbia University","United States","North America","compute",2004,"Started by building statistical point-process models for neural spike trains and encoding.","Develops scalable inference for electrophysiology, calcium imaging and closed-loop experiments.",["spikesort","calcium","decoder"],"https://www.stat.columbia.edu/~liam/",[{year:2010,title:"Fast neural decoding",detail:"Advanced Bayesian state-space methods for neural populations."},{year:2017,title:"CaImAn",detail:"Co-developed open, scalable calcium-imaging analysis."}]],
  ["jonathan-pillow","Jonathan Pillow","Princeton University","United States","North America","compute",2008,"Started by using generalized linear models to explain how retinal populations jointly encode stimuli.","Builds probabilistic models for neural coding, behavior and adaptive experiment design.",["decoder","neuralcode","digitaltwin"],"https://pillowlab.princeton.edu/",[{year:2011,title:"Population coding models",detail:"Linked shared variability and coupling to more accurate neural decoding."},{year:2020,title:"Flexible latent-state inference",detail:"Extended statistical tools to complex behavior and large populations."}]],
  ["mackenzie-mathis","Mackenzie Mathis","EPFL","Switzerland","Europe","compute",2018,"Started by creating DeepLabCut to make markerless animal pose estimation accessible to neuroscience laboratories.","Connects computer vision, motor control and behavior quantification across species.",["decoder","digitaltwin","motorbci"],"https://www.mathislab.org/",[{year:2020,title:"Multi-animal and 3D pose",detail:"Expanded markerless tracking to richer social and biomechanical settings."},{year:2024,title:"Foundation models for behavior",detail:"Pursued generalizable representations linking movement and neural activity."}]],
  ["alexander-mathis","Alexander Mathis","Harvard University","United States","North America","compute",2018,"Started by co-creating DeepLabCut and analyzing neural representations of movement.","Develops computational theories and machine-learning tools for sensorimotor intelligence.",["decoder","digitaltwin","neuralcode"],"https://www.mathisgroup.org/",[{year:2021,title:"Sensorimotor representation models",detail:"Connected pose, task structure and neural population activity."},{year:2024,title:"Generalist behavioral models",detail:"Expanded learning systems across animals, tasks and recording conditions."}]],
  ["kristofer-bouchard","Kristofer Bouchard","Lawrence Berkeley National Laboratory","United States","North America","compute",2013,"Started by decoding the articulatory organization of human speech sensorimotor cortex.","Builds interpretable machine learning for speech, neural dynamics and scientific foundation models.",["speechecog","decoder","digitaltwin"],"https://biosciences.lbl.gov/profiles/kristofer-bouchard/",[{year:2016,title:"Cortical speech dynamics",detail:"Modeled how neural populations coordinate articulators over time."},{year:2024,title:"AI for scientific neural data",detail:"Linked large-scale machine learning with multimodal biological measurements."}]],
  ["satrajit-ghosh","Satrajit Ghosh","MIT","United States","North America","personal",2011,"Started by building reproducible neuroimaging workflows and the Nipype software ecosystem.","Leads open standards, data-sharing and computational infrastructure across neuroimaging and behavior.",["bids","openneuro","digitaltwin"],"https://satra.cogitatum.org/",[{year:2016,title:"Reproducible neuroimaging ecosystems",detail:"Connected BIDS-compatible workflows, containers and shared derivatives."},{year:2021,title:"Open multimodal data",detail:"Expanded standards and platforms for collaborative human neuroscience."}]],
  ["yaroslav-halchenko","Yaroslav Halchenko","Dartmouth College","United States","North America","personal",2006,"Started by creating open multivariate analysis software for neuroimaging and machine learning.","Co-developed DataLad and reproducible data logistics for large neuroscience datasets.",["bids","openneuro","nwb"],"https://centerforopenneuroscience.org/",[{year:2016,title:"DataLad",detail:"Introduced distributed versioned data management for scientific files."},{year:2020,title:"Open neuroscience infrastructure",detail:"Linked datasets, code and provenance across analysis environments."}]],
  ["michael-linderman","Scott Linderman","Stanford University","United States","North America","compute",2016,"Started by building Bayesian latent-state models for neural population dynamics.","Develops probabilistic tools that connect interpretable circuit models with large-scale recordings.",["decoder","neuralcode","digitaltwin"],"https://slinderman.github.io/",[{year:2018,title:"Switching dynamical systems",detail:"Modeled discrete behavioral states and continuous neural trajectories together."},{year:2023,title:"Scalable probabilistic neuroscience",detail:"Expanded modern inference to high-dimensional, multimodal neural data."}]],
  ["jeremy-magland","Jeremy Magland","Simons Foundation / Flatiron Institute","United States","North America","compute",2017,"Started neurotechnology work by developing MountainSort and reproducible spike-sorting validation.","Builds open electrophysiology tools, SpikeForest benchmarking and large-data infrastructure.",["spikesort","nwb","neuropixels"],"https://www.simonsfoundation.org/people/jeremy-magland/",[{year:2020,title:"SpikeForest",detail:"Created a reproducible comparison service for spike-sorting algorithms."},{year:2024,title:"Scalable electrophysiology software",detail:"Continued open tooling for curation, formats and community benchmarks."}]],

  ["judy-illes","Judy Illes","University of British Columbia","Canada","North America","personal",2002,"Started by studying the ethical and social implications of brain imaging and incidental findings.","Established neuroethics programs spanning imaging, devices, Indigenous engagement and global governance.",["neuroethics","fmri","consumer"],"https://neuroethics.med.ubc.ca/",[{year:2006,title:"Neuroethics as a field",detail:"Helped define practical ethics questions created by rapidly advancing neuroscience."},{year:2020,title:"Global neuroethics",detail:"Expanded governance work across cultures, access and emerging devices."}]],
  ["martha-farah","Martha Farah","University of Pennsylvania","United States","North America","personal",2002,"Started neuroethics work from cognitive neuroscience questions about enhancement, prediction and personhood.","Built interdisciplinary scholarship on imaging, poverty, brain enhancement and responsible translation.",["neuroethics","fmri","consumer"],"https://neuroethics.upenn.edu/",[{year:2005,title:"Cognitive neuroethics agenda",detail:"Framed social implications of reading and modifying human cognition."},{year:2017,title:"Evidence and policy",detail:"Connected neuroscience claims with education, inequality and public decision-making."}]],
  ["nita-farahany","Nita Farahany","Duke University","United States","North America","personal",2012,"Started at the intersection of law, genetics and neuroscience, focusing on responsibility and mental privacy.","Studies workplace neurotechnology, cognitive liberty and legal protections for brain data.",["neuroethics","consumer","eeg"],"https://scienceandsociety.duke.edu/people/nita-farahany/",[{year:2018,title:"Consumer brain-data governance",detail:"Examined how wearable neural data could be inferred, traded and regulated."},{year:2023,title:"Cognitive liberty framework",detail:"Synthesized legal and social protections for increasingly measurable mental states."}]],
  ["marcello-ienca","Marcello Ienca","Technical University of Munich","Germany","Europe","personal",2015,"Started by analyzing ethical issues in brain-computer interfaces, cognitive enhancement and machine intelligence.","Advanced neurorights, mental privacy and responsible neurotechnology governance.",["neuroethics","motorbci","consumer"],"https://www.ieai.sot.tum.de/people/marcello-ienca/",[{year:2017,title:"Neurorights proposal",detail:"Helped articulate rights to mental privacy, identity and agency."},{year:2021,title:"International governance",detail:"Connected ethics frameworks with policy efforts across jurisdictions."}]],
  ["saskia-hendriks","Saskia Hendriks","NIH BRAIN Initiative","United States","North America","personal",2018,"Started by bringing empirical bioethics into NIH neurotechnology and human-neuroscience programs.","Coordinates neuroethics integration, participant perspectives and responsible research practices.",["neuroethics","dbs","motorbci"],"https://braininitiative.nih.gov/research/neuroethics",[{year:2019,title:"BRAIN neuroethics integration",detail:"Embedded ethics questions within funded technology and human-research programs."},{year:2023,title:"Participant-centered guidance",detail:"Expanded attention to consent, identity, data and long-term device responsibilities."}]],
  ["joseph-fins","Joseph Fins","Weill Cornell Medicine","United States","North America","personal",2005,"Started neuroethics work through disorders of consciousness, clinical decision-making and patient rights.","Connects severe brain injury, neuromodulation trials and obligations to participants and families.",["neuroethics","dbs","eeg"],"https://weillcornell.org/joseph-fins",[{year:2007,title:"DBS and consciousness",detail:"Analyzed emerging stimulation studies for minimally conscious patients."},{year:2015,title:"Rights after severe brain injury",detail:"Linked scientific advances to rehabilitation access and social recognition."}]],
  ["laura-cabrera","Laura Cabrera","Penn State University","United States","North America","personal",2014,"Started by studying public attitudes and ethical tradeoffs surrounding psychiatric and enhancement neurotechnologies.","Works on DBS, non-invasive stimulation, responsibility and stakeholder engagement.",["neuroethics","dbs","tes"],"https://bioethics.psu.edu/people/laura-cabrera/",[{year:2018,title:"Public perspectives on neuromodulation",detail:"Examined how patients and communities weigh benefit, identity and risk."},{year:2023,title:"Responsible device translation",detail:"Integrated empirical ethics with clinical and engineering collaborations."}]],
  ["jennifer-chandler","Jennifer Chandler","University of Ottawa","Canada","North America","personal",2015,"Started from legal questions around brain interventions, personality change and responsibility.","Studies neuroprostheses, psychiatric neurosurgery, privacy and the law of human-machine integration.",["neuroethics","dbs","bionichand"],"https://www.uottawa.ca/faculty-law/civil-law/people/chandler-jennifer",[{year:2019,title:"Law of neuroprostheses",detail:"Analyzed agency, liability and identity in implanted and assistive systems."},{year:2022,title:"International neurotechnology law",detail:"Connected clinical cases with emerging rights and regulatory proposals."}]],
  ["jonathan-moreno","Jonathan Moreno","University of Pennsylvania","United States","North America","personal",2003,"Started neuroethics work from national-security, bioethics and human-subject research questions.","Examines military neuroscience, cognitive enhancement and public governance of brain technologies.",["neuroethics","tms","consumer"],"https://neuroethics.upenn.edu/",[{year:2006,title:"Neuroscience and national security",detail:"Mapped defense interest in cognition, performance and brain intervention."},{year:2012,title:"Mind Wars",detail:"Brought military and policy dimensions of neurotechnology to a wider audience."}]],
  ["timothy-brown","Timothy Brown","University of Washington","United States","North America","personal",2016,"Started by studying agency, authenticity and disability perspectives in deep-brain stimulation and BCIs.","Uses philosophical and participatory methods to shape responsible neural-device design.",["neuroethics","dbs","motorbci"],"https://depts.washington.edu/neuroethics/",[{year:2020,title:"Agency in adaptive stimulation",detail:"Examined how closed-loop systems redistribute control between users and devices."},{year:2024,title:"Participatory neuroethics",detail:"Integrated lived experience into design and governance discussions."}]]
];

function researcherLiteratureUrl(name: string): string {
  return "https://pubmed.ncbi.nlm.nih.gov/?term=" + encodeURIComponent(name + "[Author]");
}

const researcherTechnologyAliases: Record<string,string> = {
  bids: "nwb",
  ecogflex: "ecog",
  handwriting: "motorbci",
  lfp: "eeg",
  mesoscope: "calcium",
  miniscope: "calcium",
  nanowire: "silicon",
  neuroethics: "brainfoundation",
  openneuro: "nwb",
  spatialomics: "cellatlas",
  twophoton: "calcium",
  wearable: "consumer"
};

const researcherProfileOverrides: Record<string,string> = {
  "frank-willett": "https://profiles.stanford.edu/francis-willett",
  "jose-millan": "https://bme.utexas.edu/people/faculty-directory/millan",
  "andrew-schwartz": "https://www.cnup.pitt.edu/people/andrew-b-schwartz-phd",
  "dustin-tyler": "https://engineering.case.edu/about/school-directory/dustin-tyler",
  "peter-brown": "https://www.neuroscience.ox.ac.uk/news/retirement-of-professor-peter-brown",
  "cameron-mcintyre": "https://engineering.case.edu/about/school-directory/cameron-mcintyre",
  "georg-nagel": "https://www.biozentrum.uni-wuerzburg.de/en/bot1/research/prof-dr-georg-nagel/",
  "kristofer-bouchard": "https://biosciences.lbl.gov/profiles/kristofer-e-bouchard/",
  "michael-linderman": "https://web.stanford.edu/~swl1/",
  "joseph-fins": "https://teach.weill.cornell.edu/person/joseph-j-fins",
  "laura-cabrera": "https://philosophy.la.psu.edu/people/laura-cabrera/"
};

const researchers: ResearcherTrail[] = researcherSeeds.map(function(seed){
  return {
    id: seed[0] === "michael-linderman" ? "scott-linderman" : seed[0], name: seed[1], institution: seed[2], country: seed[3], region: seed[4], group: seed[5],
    startYear: seed[6], start: seed[7], summary: seed[8], techIds: Array.from(new Set(seed[9].map(function(id){ return researcherTechnologyAliases[id] || id; }))), profileUrl: researcherProfileOverrides[seed[0]] || seed[10],
    literatureUrl: researcherLiteratureUrl(seed[1]), milestones: seed[11]
  };
});
