interface VisualImage {url:string;alt:string;caption:string;credit:string;source:string;usage?:string;license?:{label:string;url:string};}
interface VisualVideo {id:string;title:string;channel:string;source:string;description:string;}
interface VisualResearch {labId:string;title:string;image:VisualImage;video?:VisualVideo;focus:string;kind:string;}
interface VisualItem {id:string;title:string;owner:string;group:string;image:VisualImage;video?:VisualVideo;focus:string;kind:string;href:string;}
declare var neuroVisualData:{reviewed:string;items:VisualResearch[]};

// Research photos remain on their original institutional hosts. Illustrations
// and photo captions always identify what the image actually represents.
const NeuroVisuals=(()=>{
 const e=hubUtils.escapeHtml,u=hubUtils.sourceHref;
 const play='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 11 7-11 7Z"/></svg>';
 function items():VisualItem[]{
  return [...neuroIdeasData.companies.map((c:any)=>({id:'company-'+c.id,title:c.visual?.name||c.name,owner:c.name,group:'companies',image:c.media.image,video:c.media.video,focus:c.thought,kind:c.media.image.kind,href:'#ideas/moores-law-bci?section=companies&company='+c.id})),
   ...neuroVisualData.items.map(m=>{const l=neuroLabsData.labs.find(l=>l.id===m.labId)!;return {id:'lab-'+m.labId,title:m.title,owner:l.name+' · '+l.institution,group:'labs',image:m.image,video:m.video,focus:m.focus,kind:m.kind,href:'#labs/'+m.labId};}),
   ...(typeof neuroConnectionsData!=='undefined'?neuroConnectionsData.nodes.filter(n=>n.image).map(n=>({id:'person-'+n.id,title:n.name,owner:n.subtitle,group:'people',image:n.image!,focus:n.summary,kind:'portrait',href:'#connections/'+n.id})):[])];
 }
 function picture(m:VisualItem,priority=false){return `<div class="visual-image"><span class="visual-image-missing">Image unavailable here.<br>Open the credited source below.</span><img data-visual-image src="${u(m.image.url)}" alt="${e(m.image.alt)}" loading="${priority?'eager':'lazy'}" decoding="async"></div>`;}
 function thumb(m:VisualItem,priority=false){return `<button class="visual-enlarge" type="button" data-visual-open="${e(m.id)}" aria-label="Enlarge image: ${e(m.title)}">${picture(m,priority)}<span class="visual-enlarge-label" aria-hidden="true">View image <b>⤢</b></span></button>`;}
 function credit(m:VisualItem){return `<figcaption class="visual-credit"><span>${e(m.image.caption)}</span><a href="${u(m.image.source)}" target="_blank" rel="noopener noreferrer">${e(m.image.credit)} ↗</a>${m.image.license?`<a href="${u(m.image.license.url)}" target="_blank" rel="noopener noreferrer">${e(m.image.license.label)} · image unmodified ↗</a>`:''}</figcaption>`;}
 function card(m:VisualItem){return `<article class="visual-card"><figure>${thumb(m)}${credit(m)}</figure><div class="visual-card-copy"><span class="visual-owner">${e(m.owner)}</span><h2><a href="${e(m.href)}">${e(m.title)} <span aria-hidden="true">↗</span></a></h2><p>${e(m.focus)}</p><div class="visual-card-actions"><a href="${e(m.href)}">Explore the research →</a>${m.video?`<button type="button" class="visual-watch" data-visual-open="${e(m.id)}" data-visual-mode="video">${play} Watch film</button>`:''}</div></div></article>`;}
 function spotlight(){
  const all=items(),first=all.find(m=>m.id==='company-bisc')!,second=all.find(m=>m.group==='labs')||all[0];
  return `<section class="visual-spotlight" aria-labelledby="visual-spotlight-title"><div class="visual-spotlight-copy"><span class="eyebrow">THE VISUAL FIELD GUIDE</span><h2 id="visual-spotlight-title">See the engineering.<br>Follow the idea.</h2><p>Devices up close, research in action, and the people making it happen.</p><a href="#visuals">Explore pictures &amp; films <span aria-hidden="true">↗</span></a></div><a class="visual-spotlight-photo" href="#visuals?group=companies">${picture(first,true)}<span><small>DEVICE CLOSE-UP</small><strong>${e(first.title)} ↗</strong></span></a><a class="visual-spotlight-photo visual-spotlight-second" href="#visuals?group=labs">${picture(second,true)}<span><small>INSIDE THE LABS</small><strong>${e(second.title)} ↗</strong></span></a></section>`;
 }
 function labCard(id:string){const m=items().find(m=>m.id==='lab-'+id);return m?`<div class="lab-card-visual"><a class="lab-card-photo" href="#labs/${e(id)}">${picture(m)}<span>Research close-up <b aria-hidden="true">↗</b></span></a><a class="lab-card-photo-credit" href="${u(m.image.source)}" target="_blank" rel="noopener noreferrer">${e(m.image.credit)} ↗</a>${m.image.license?`<a class="lab-card-photo-credit" href="${u(m.image.license.url)}" target="_blank" rel="noopener noreferrer">${e(m.image.license.label)} ↗</a>`:''}</div>`:'';}
 function labFeature(id:string){const m=items().find(m=>m.id==='lab-'+id);return m?`<section class="visual-lab-feature" id="lab-profile-visuals" tabindex="-1" aria-label="Research images and film"><figure>${thumb(m,true)}${credit(m)}</figure><div class="visual-lab-caption"><span class="eyebrow">RESEARCH IN VIEW</span><h2>${e(m.title)}</h2><p>${e(m.focus)}</p>${m.video?`<div class="visual-media">${NeuroMedia.video({media:{video:m.video}})}</div>`:`<a href="${u(m.image.source)}" target="_blank" rel="noopener noreferrer">Read the institutional story ↗</a>`}<a class="visual-all-link" href="#visuals?group=labs">More research pictures &amp; films →</a></div></section>`:'';}
 function labBanner(){return `<a class="visual-lab-banner" href="#visuals?group=labs"><span>${play}<strong>Explore the research visually</strong><small>Device photographs, experiments, and university films</small></span><b aria-hidden="true">↗</b></a>`;}
 function countCopy(step:number,bank:number){
  return [
   `<span class="visual-count-kicker">STEP 1 OF 3 · THE HARDWARE</span><h3>32 physical sites</h3><p>Each dot is a contact on this imaginary probe. There are 32 places where it could sample electrical activity.</p><p class="visual-count-takeaway">A physical site is a place to measure. It is not a count of neurons.</p>`,
   `<span class="visual-count-kicker">STEP 2 OF 3 · THE READOUT</span><h3>8 simultaneous channels</h3><p>This example reads 8 selected contacts at once. The other 24 contacts are still on the probe, but are not being read now.</p><p class="visual-count-takeaway">Group ${bank+1} of 4 selected. Change the group below: the probe still has 32 sites and the readout still has 8 channels.</p>`,
   `<span class="visual-count-kicker">STEP 3 OF 3 · THE ANALYSIS</span><h3>6 example units</h3><p>Spike sorting groups recorded spikes into putative neurons, called units. Imagine that analysis identifies 6 units in these recordings.</p><p class="visual-count-takeaway">One unit can appear on several channels, and one channel can detect several units. Six is an invented result, not a calculation from eight.</p>`
  ][step];
 }
 function explainer(){return `<section class="visual-count-story" aria-labelledby="count-story-title"><header><span class="eyebrow">ONE ILLUSTRATIVE EXAMPLE</span><h2 id="count-story-title">32 sites. 8 channels. 6 units.</h2><p>These describe three different measurements. Follow the hardware, readout and analysis to see why the counts differ.</p></header><div class="visual-count-steps" role="group" aria-label="Choose a step in the neural-count example">${[['32','Physical sites'],['8','Simultaneous channels'],['6','Example units']].map(([n,t],i)=>`<button type="button" data-count-step="${i}" aria-pressed="${i===0}" aria-controls="visual-count-art visual-count-copy"><span class="visual-count-step-number">${i+1}</span><strong>${n}</strong><span>${t}</span></button>`).join('')}</div><div class="visual-count-layout"><div class="visual-count-stage"><div class="visual-count-art" id="visual-count-art">${countFrame(0,0)}</div><p>Illustrative diagram · invented numbers and waveforms</p></div><div class="visual-count-reader"><div id="visual-count-copy" role="status" aria-live="polite" aria-atomic="true">${countCopy(0,0)}</div><button id="visual-count-bank" type="button" hidden>Sample another group of 8 ↻</button><div class="visual-count-navigation" role="group" aria-label="Move through the count example"><button id="visual-count-prev" type="button" disabled>← Previous</button><span id="visual-count-position">Step 1 of 3</span><button id="visual-count-next" type="button">Next: channels →</button></div><a href="#ideas/moores-law-bci?section=counts">Compare real systems and historical counts →</a></div></div></section>`;}
 function render(params=new URLSearchParams()){
  const all=items(),requested=params.get('group')||'',group=['companies','labs','people','explainers'].includes(requested)?requested:'companies';
  const selected=all.filter(m=>m.group===group),films=selected.filter(m=>m.video).length;
  const titles:Record<string,string>={companies:'Device pictures',labs:'In the lab',people:'People',explainers:'How to read neural counts'};
  const descriptions:Record<string,string>={companies:'See the shape and scale of neural interfaces. Captions identify photographs, renders and research figures.',labs:'Look inside the experiments and watch demonstrations from university and lab sources.',people:'Sourced portraits connect a face to the research. Explore the people directory for broader coverage.'};
  const heading=`<div class="visual-gallery-heading"><div><h2 id="visual-gallery-title">${titles[group]}</h2><p>${descriptions[group]||''}</p></div><span>${selected.length} ${group==='people'?'portrait'+(selected.length===1?'':'s'):'stories'}${films?' · '+films+' film'+(films===1?'':'s'):''}</span></div>`;
  return `<div class="visual-page" data-visual-group="${group}"><header class="visual-page-head"><span class="eyebrow">LOOK CLOSER</span><h1>Pictures &amp; films</h1><p>See the devices and experiments behind the research, or learn how to read their neural counts.</p></header><nav class="visual-tabs" aria-label="Pictures and films sections">${Object.entries(titles).map(([key,label])=>`<a href="#visuals?group=${key}"${key===group?' aria-current="page"':''}>${label}</a>`).join('')}</nav>${group==='explainers'?explainer():`<section aria-labelledby="visual-gallery-title">${heading}${group==='people'?`<a class="visual-people-link" href="#people"><span><strong>Explore the people directory</strong><small>Researchers, founders and the work that connects them</small></span><b aria-hidden="true">→</b></a>`:''}<p class="visual-gallery-help">Select a picture to enlarge it.${films?' Use “Watch film” to open a video.':''} Source credits appear beneath every image.</p><div class="visual-grid${group==='people'?' visual-grid-people':''}">${selected.map(card).join('')}</div></section>`}${group==='explainers'?'':`<p class="visual-source-note">Pictures remain on their original source websites. Films load from YouTube only when you press play.</p>`}</div>`;
 }
 function countFrame(step:number,bank:number){
  // The last frame deliberately groups all recordings before showing units.
  // A wire from one channel to one unit would imply an unsupported mapping.
  const selected=Array.from({length:8},(_,i)=>i+bank*8),accent='#83e5d2',faint='#405b6b';
  const sites=Array.from({length:32},(_,i)=>{const x=57+(i%4)*27,y=61+Math.floor(i/4)*27,on=step===0||selected.includes(i);return `<circle data-count-site="${i}" data-selected="${on}" cx="${x}" cy="${y}" r="6.5" fill="${on?accent:faint}"${on?' stroke="#c6fff1" stroke-width="1"':''}/>`;}).join('');
  const probe=`<rect x="34" y="36" width="126" height="240" rx="20" fill="#233e4d" stroke="#68838c"/>${sites}<text x="97" y="302" text-anchor="middle" fill="#d0e4e8" font-size="14">32 physical sites</text>`;
  const trace=(x:number,y:number,w:number,color:string)=>`<path d="M ${x} ${y} h ${w*.22} l 4 -4 4 9 4 -18 4 16 4 -3 h ${w*.22}" stroke="${color}" stroke-width="1.5" fill="none"/>`;
  const readout=`<path d="M 167 153 H 197 m -6 -5 6 5 -6 5" stroke="${accent}" stroke-width="2" fill="none"/><rect x="207" y="42" width="155" height="237" rx="12" fill="#1b3848" stroke="#64808d"/><text x="285" y="64" text-anchor="middle" fill="#d0e4e8" font-size="13">Read at the same time</text>${selected.map((site,i)=>`<text x="219" y="${90+i*24}" fill="#a6c4cf" font-size="10">${i+1}</text><g data-count-channel="${i}">${trace(234,86+i*24,145,accent)}</g>`).join('')}<text x="285" y="302" text-anchor="middle" fill="#d0e4e8" font-size="14">8 channels</text>`;
  const recording=Array.from({length:8},(_,i)=>`<g data-count-channel="${i}">${trace(34+i%4*88,55+Math.floor(i/4)*32,72,accent)}</g>`).join('');
  const units=Array.from({length:6},(_,i)=>`<g data-count-unit="${i}"><rect x="${24+i*59}" y="222" width="53" height="54" rx="8" fill="#e1f2ec"/><text x="${50+i*59}" y="246" text-anchor="middle" fill="#214f4c" font-size="12">Unit</text><text x="${50+i*59}" y="265" text-anchor="middle" fill="#214f4c" font-size="15" font-weight="700">${i+1}</text></g>`).join('');
  const sorting=`<text x="198" y="23" text-anchor="middle" fill="#d0e4e8" font-size="14">Recordings from 8 channels</text><rect x="22" y="33" width="356" height="68" rx="9" fill="#233e4d" stroke="#68838c"/>${recording}<path d="M 198 104 v 19 m -5 -5 5 5 5 -5" stroke="${accent}" stroke-width="2" fill="none"/><rect x="89" y="132" width="218" height="47" rx="9" fill="#3e625f"/><text x="198" y="161" text-anchor="middle" fill="#ecfff9" font-size="17" font-weight="600">Spike sorting</text><path d="M 198 183 v 26 m -5 -5 5 5 5 -5" stroke="${accent}" stroke-width="2" fill="none"/>${units}<text x="198" y="302" text-anchor="middle" fill="#d0e4e8" font-size="14">6 units in this invented result</text>`;
  const labels=['32 physical sites on one illustrative probe; a site is a place to measure','8 of the 32 sites are selected and recorded through 8 simultaneous channels','Recordings from 8 channels are analyzed together by spike sorting; 6 example units are identified, with no one-to-one channel mapping'];
  return `<svg viewBox="0 0 400 326" role="img" aria-label="${labels[step]}" font-family="inherit">${step===2?sorting:probe+(step===1?readout:`<text x="271" y="130" text-anchor="middle" fill="${accent}" font-size="68" font-weight="700">32</text><text x="271" y="163" text-anchor="middle" fill="#d0e4e8" font-size="16">places to measure</text><text x="271" y="214" text-anchor="middle" fill="#a6c4cf" font-size="13">All contacts are shown.</text>`)}</svg>`;
 }
 function bind(container:HTMLElement){
  container.querySelectorAll<HTMLImageElement>('[data-visual-image]').forEach(img=>{if(img.dataset.visualBound)return;img.dataset.visualBound='true';const fail=()=>{img.hidden=true;img.parentElement?.classList.add('visual-image-failed');};img.addEventListener('error',fail,{once:true});if(img.complete&&!img.naturalWidth)fail();});
  container.querySelectorAll<HTMLElement>('.visual-media').forEach(node=>NeuroMedia.bind(node));
  container.querySelectorAll<HTMLButtonElement>('[data-visual-open]').forEach(button=>{if(button.dataset.visualBound)return;button.dataset.visualBound='true';button.addEventListener('click',()=>open(button.dataset.visualOpen!,button.dataset.visualMode==='video',button));});
  const stage=container.querySelector<HTMLElement>('#visual-count-art');if(!stage||stage.dataset.countBound)return;
  stage.dataset.countBound='true';
  let step=0,bank=0;
  const copy=container.querySelector<HTMLElement>('#visual-count-copy')!,switcher=container.querySelector<HTMLButtonElement>('#visual-count-bank')!;
  const previous=container.querySelector<HTMLButtonElement>('#visual-count-prev')!,next=container.querySelector<HTMLButtonElement>('#visual-count-next')!,position=container.querySelector<HTMLElement>('#visual-count-position')!;
  const steps=container.querySelectorAll<HTMLButtonElement>('[data-count-step]');
  const update=()=>{stage.innerHTML=countFrame(step,bank);copy.innerHTML=countCopy(step,bank);switcher.hidden=step!==1;previous.disabled=step===0;next.disabled=step===2;next.textContent=step===0?'Next: channels →':step===1?'Next: units →':'End of example';position.textContent=`Step ${step+1} of 3`;steps.forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.countStep)===step)));};
  const go=(value:number)=>{step=Math.max(0,Math.min(2,value));update();};
  steps.forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.countStep))));
  previous.addEventListener('click',()=>{go(step-1);if(previous.disabled)next.focus({preventScroll:true});});next.addEventListener('click',()=>{go(step+1);if(next.disabled)previous.focus({preventScroll:true});});
  switcher.addEventListener('click',()=>{bank=(bank+1)%4;update();});update();
 }
 let returnFocus:HTMLElement|null=null,dialogBound=false;
 function close(){const dialog=document.getElementById('visual-lightbox') as HTMLDialogElement;if(dialog?.open)dialog.close();}
 function open(id:string,watch:boolean,trigger:HTMLElement){
  const m=items().find(m=>m.id===id),dialog=document.getElementById('visual-lightbox') as HTMLDialogElement;if(!m||!dialog)return;
  returnFocus=trigger;
  if(!dialogBound){dialog.querySelector('[data-visual-close]')!.addEventListener('click',close);dialog.addEventListener('click',event=>{if(event.target===dialog)close();});dialog.addEventListener('close',()=>{dialog.querySelector('#visual-lightbox-content')!.innerHTML='';document.body.classList.remove('visual-open');if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});});dialogBound=true;}
  const body=dialog.querySelector<HTMLElement>('#visual-lightbox-content')!;
  const video=Boolean(watch&&m.video);
  dialog.querySelector('#visual-lightbox-title')!.textContent=m.title;
  body.innerHTML=`${video?`<div class="visual-lightbox-video">${NeuroMedia.video({media:{video:m.video}})}</div>`:`<figure>${picture(m,true)}${credit(m)}</figure>`}<div class="visual-lightbox-caption"><span>${e(m.owner)}</span><p>${e(m.focus)}</p>${m.group==='labs'?`<p>${e(neuroLabsData.labs.find(l=>'lab-'+l.id===m.id)!.summary)}</p>`:''}<div><a href="${e(m.href)}" data-visual-follow>Explore the research →</a>${m.video?`<button type="button" data-visual-toggle>${video?'View research image':'Watch the film'}</button>`:''}</div></div>`;
  body.querySelector('[data-visual-toggle]')?.addEventListener('click',()=>open(id,!video,trigger));body.querySelector('[data-visual-follow]')?.addEventListener('click',close);
  bind(body);if(video)NeuroMedia.bind(body);
  if(!dialog.open)dialog.showModal();document.body.classList.add('visual-open');
  // Showing the poster first makes playing a video an explicit user action.
  if(video)body.querySelector<HTMLButtonElement>('[data-neuro-video]')?.focus();
  else dialog.querySelector<HTMLButtonElement>('[data-visual-close]')?.focus();
 }
 function idea(id:string){
  const imageId:Record<string,string>={'moores-law-bci':'lab-rice-xie','density-or-coverage':'company-precision','useful-channels':'lab-rice-luan','readout-budget':'company-bisc'};
  const m=items().find(m=>m.id===imageId[id]);if(!m)return '';
  const labels:Record<string,string>={'moores-law-bci':'One probe. Several different counts.','density-or-coverage':'The same number, in different places.','useful-channels':'Follow the signal all the way through.','readout-budget':'Every sample has to travel somewhere.'};
  const dots=(start:number,gap:number)=>Array.from({length:16},(_,i)=>`<circle cx="${start+i%4*gap}" cy="${55+Math.floor(i/4)*gap}" r="3.5" fill="#55b7a5"/>`).join('');
  const rows=id==='density-or-coverage'?`<rect x="30" y="26" width="135" height="140" rx="16" fill="#244c59"/><rect x="205" y="26" width="135" height="140" rx="16" fill="#244c59"/>${dots(68,12)}${dots(227,30)}<text x="98" y="195" text-anchor="middle">16 dense contacts</text><text x="273" y="195" text-anchor="middle">16 spread contacts</text>`:
   id==='moores-law-bci'?`<g>${Array.from({length:3},(_,i)=>`<rect x="${22+i*118}" y="35" width="104" height="114" rx="12" fill="#244c59"/><text x="${74+i*118}" y="89" text-anchor="middle" font-size="33" fill="#8cdfcb">${[32,8,6][i]}</text><text x="${74+i*118}" y="122" text-anchor="middle">${['sites','channels','units'][i]}</text>`).join('')}</g><text x="190" y="182" text-anchor="middle">Different measurements of one example</text>`:
   (id==='useful-channels'?['Implanted','Recorded','Quality checked','Decoder input']:['Contacts','Digitize','Transmit','Store']).map((label,i)=>`<rect x="${14+i*93}" y="53" width="81" height="74" rx="9" fill="#244c59"/><text x="${54+i*93}" y="94" text-anchor="middle" font-size="${label.length>10?9:11}">${label}</text>${i<3?`<path d="M ${98+i*93} 90 h 8 m -4 -4 4 4 -4 4" stroke="#8cdfcb" fill="none"/>`:''}`).join('');
  return `<aside class="idea-visual-aside"><figure>${thumb(m,true)}${credit(m)}</figure><div class="idea-concept"><span>EXPLANATORY DIAGRAM</span><h2>${e(labels[id])}</h2><svg viewBox="0 0 390 220" role="img" aria-label="${e(labels[id])}" fill="#cfe4e7" font-family="inherit" font-size="12">${rows}</svg><p>${id==='moores-law-bci'?'Illustrative numbers, not a product specification.':id==='density-or-coverage'?'Illustrative geometry. Neither arrangement is assumed to perform better.':id==='useful-channels'?'Report each stage separately and repeat at fixed follow-up times.':'A conceptual data path. Storage demand follows channels × sample rate × bit depth.'}</p>${id==='moores-law-bci'?'<a href="#visuals?group=explainers">Try selecting different contacts →</a>':''}</div></aside>`;
 }
 function records():HubRecord[]{return items().map(m=>({id:m.id,title:m.title,description:m.focus,kind:'Visual story',href:m.href,keywords:m.owner+' picture image video film'}));}
 return {items,render,spotlight,labCard,labFeature,labBanner,bind,close,records,countFrame,idea,explainer,credit,picture};
})();
